/***************************************************************************
 *     Copyright (c) 1999-2005, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * $brcm_Workfile: bchp_uartc.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 6/2/05 7:52p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Thu Jun  2 18:49:22 2005
 *                 MD5 Checksum         a50f0fc6364fcf024e7939ceb7259334
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.006
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7401/rdb/a0/bchp_uartc.h $
 * 
 * Hydra_Software_Devel/1   6/2/05 7:52p jasonh
 * PR 15748: Initial version.
 *
 ***************************************************************************/

#ifndef BCHP_UARTC_H__
#define BCHP_UARTC_H__

/***************************************************************************
 *UARTC - UART C
 ***************************************************************************/
#define BCHP_UARTC_RCVSTAT                       0x004001c0 /* RECEIVE STATUS REGISTER */
#define BCHP_UARTC_RCVDATA                       0x004001c4 /* RECEIVE DATA REGISTER */
#define BCHP_UARTC_CONTROL                       0x004001cc /* CONTROL REGISTER */
#define BCHP_UARTC_BAUDHI                        0x004001d0 /* BAUD RATE REGISTER HI */
#define BCHP_UARTC_BAUDLO                        0x004001d4 /* BAUD RATE REGISTER LO */
#define BCHP_UARTC_XMTSTAT                       0x004001d8 /* TRANSMIT STATUS REGISTER */
#define BCHP_UARTC_XMTDATA                       0x004001dc /* TRANSMIT DATA REGISTER */

#endif /* #ifndef BCHP_UARTC_H__ */

/* End of File */
