/* 
 * Copyright (C) 2009 Gulessoft , Inc. 
 * Written by Guo Hongruan (guo.hongruan@gulessoft.com)
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version
 * 2 of the License, or (at your option) any later version.
 */

#ifndef __ASM_IRQ_INTERNAL_H
#define __ASM_IRQ_INTERNAL_H

#define IRQ_HANDLER(irq)     	 	IRQ##irq##_handler
#define DECLEAR_IRQ_HANDLER(irq) 	extern void IRQ_HANDLER(irq)(void)

DECLEAR_IRQ_HANDLER(0);
DECLEAR_IRQ_HANDLER(1);
DECLEAR_IRQ_HANDLER(2);
DECLEAR_IRQ_HANDLER(3);
DECLEAR_IRQ_HANDLER(4);
DECLEAR_IRQ_HANDLER(5);
DECLEAR_IRQ_HANDLER(6);
DECLEAR_IRQ_HANDLER(7);
DECLEAR_IRQ_HANDLER(8);
DECLEAR_IRQ_HANDLER(9);
DECLEAR_IRQ_HANDLER(10);
DECLEAR_IRQ_HANDLER(11);
DECLEAR_IRQ_HANDLER(12);
DECLEAR_IRQ_HANDLER(13);
DECLEAR_IRQ_HANDLER(14);
DECLEAR_IRQ_HANDLER(15);
DECLEAR_IRQ_HANDLER(16);
DECLEAR_IRQ_HANDLER(17);
DECLEAR_IRQ_HANDLER(18);
DECLEAR_IRQ_HANDLER(19);
DECLEAR_IRQ_HANDLER(20);
DECLEAR_IRQ_HANDLER(21);
DECLEAR_IRQ_HANDLER(22);
DECLEAR_IRQ_HANDLER(23);
DECLEAR_IRQ_HANDLER(24);
DECLEAR_IRQ_HANDLER(25);
DECLEAR_IRQ_HANDLER(26);
DECLEAR_IRQ_HANDLER(27);
DECLEAR_IRQ_HANDLER(28);
DECLEAR_IRQ_HANDLER(29);
DECLEAR_IRQ_HANDLER(30);
DECLEAR_IRQ_HANDLER(31);
DECLEAR_IRQ_HANDLER(32);
DECLEAR_IRQ_HANDLER(33);
DECLEAR_IRQ_HANDLER(34);
DECLEAR_IRQ_HANDLER(35);
DECLEAR_IRQ_HANDLER(36);
DECLEAR_IRQ_HANDLER(37);
DECLEAR_IRQ_HANDLER(38);
DECLEAR_IRQ_HANDLER(39);
DECLEAR_IRQ_HANDLER(40);
DECLEAR_IRQ_HANDLER(41);
DECLEAR_IRQ_HANDLER(42);
DECLEAR_IRQ_HANDLER(43);
DECLEAR_IRQ_HANDLER(44);
DECLEAR_IRQ_HANDLER(45);
DECLEAR_IRQ_HANDLER(46);
DECLEAR_IRQ_HANDLER(47);
DECLEAR_IRQ_HANDLER(48);
DECLEAR_IRQ_HANDLER(49);
DECLEAR_IRQ_HANDLER(50);
DECLEAR_IRQ_HANDLER(51);
DECLEAR_IRQ_HANDLER(52);
DECLEAR_IRQ_HANDLER(53);
DECLEAR_IRQ_HANDLER(54);
DECLEAR_IRQ_HANDLER(55);
DECLEAR_IRQ_HANDLER(56);
DECLEAR_IRQ_HANDLER(57);
DECLEAR_IRQ_HANDLER(58);
DECLEAR_IRQ_HANDLER(59);
DECLEAR_IRQ_HANDLER(60);
DECLEAR_IRQ_HANDLER(61);
DECLEAR_IRQ_HANDLER(62);
DECLEAR_IRQ_HANDLER(63);

#define VIC_INTDEF(name,number,enable,level,prio)     			  \
{ 									  \
	#name,   /*name of trimedia irq info entry*/			  \
	enable,  /*does linux manage this interrupt?*/			  \
	level,   /*level triggered or edge triggered*/  		  \
	number,  /*number of irq */  					  \
	prio,     							  \
	IRQ_HANDLER(number)						  \
},

#endif /*__ASM_IRQ_INTERNAL_H*/
