rm -f arch/trimedia/bsp/intfs/Itmosal 
rm -f arch/trimedia/bsp/intfs/ItmbslPhy
rm -f arch/trimedia/bsp/tmBootInfo/tmBootInfo.c 
rm -f arch/trimedia/bsp/tmBootInfo/tmBootInfoCommon.h 
rm -f arch/trimedia/bsp/tmBootInfo/tmMemUncached.c 
rm -f arch/trimedia/bsp/tmBootInfo/tmBootInfoUtil.c 
rm -f arch/trimedia/bsp/tmBootInfo/inc 
rm -f arch/trimedia/bsp/tmbslCore/tmbslCore_vsnprintf.c
rm -f arch/trimedia/bsp/tmbslCore/tmbslCore_vsnprintf.h
rm -f arch/trimedia/bsp/tmbslCore/tmbslMgr.c
rm -f arch/trimedia/bsp/tmbslCore/tmbslOsSpecific.c
rm -f arch/trimedia/bsp/tmbslCore/inc
rm -f arch/trimedia/bsp/tmbslPnx1500/inc
rm -f arch/trimedia/bsp/tmbslTmOnly/dummy_tmtdosal.c 
rm -f arch/trimedia/bsp/tmbslTmOnly/tmbslTmOnly.c
rm -f arch/trimedia/bsp/tmbslTmOnly/tmbslTmOnly_Exception.s
rm -f arch/trimedia/bsp/tmbslTmOnly/tmbslTmOnly_OsSpecific.c
rm -f arch/trimedia/bsp/tmbslTmOnly/tmTmOnlyMmio.h
rm -f arch/trimedia/bsp/tmbslTmOnly/tmbslTmOnly.h
rm -f arch/trimedia/bsp/tmhwPci/tmhwPci.c 
rm -f arch/trimedia/bsp/tmhwPci/tmhwPciInternal.h 
rm -f arch/trimedia/bsp/tmhwPci/tmhwPciIo.c 
rm -f arch/trimedia/bsp/tmhwPci/tmhwPciMemSpace.c
rm -f arch/trimedia/bsp/tmhwPci/inc
rm -f arch/trimedia/bsp/tmhwGpio/pnx1500/tmhwGpio.c 
rm -f arch/trimedia/bsp/tmhwGpio/inc
rm -f arch/trimedia/bsp/tmhwEth/tmhwEth.c 
rm -f arch/trimedia/bsp/tmhwEth/inc 
rm -f arch/trimedia/bsp/tmhwXio/tmhwXio.c 
rm -f arch/trimedia/bsp/tmhwXio/tmhwXioInternal.h 
rm -f arch/trimedia/bsp/tmhwXio/tmhwXio_CfgLocal.h 
rm -f arch/trimedia/bsp/tmhwXio/tmhwXio_DvpCfg.c 
rm -f arch/trimedia/bsp/tmhwXio/tmhwXio_DvpNoBslCfg.c 
rm -f arch/trimedia/bsp/tmhwXio/tmvhPciXio0113_Reg.h 
rm -f arch/trimedia/bsp/tmhwXio/tmvhPciXioA051_Reg.h 
rm -f arch/trimedia/bsp/tmhwXio/inc
rm -f arch/trimedia/bsp/tmStdTypes/inc
rm -f arch/trimedia/bsp/tmbslPhyDp83847/tmbslPhyDp83847.c 
rm -f arch/trimedia/bsp/tmbslPhyDp83847/tmbslPhyDp83847RegBe.h 
rm -f arch/trimedia/bsp/tmbslPhyDp83847/tmbslPhyDp83847RegLe.h 
rm -f arch/trimedia/bsp/tmbslPhyDp83847/inc
rm -f arch/trimedia/board-mbe/gmdsbslLcp_IntDrv.h 
rm -f arch/trimedia/board-mbe/gmdsbslLcp_CoreUtilities.h 
rm -f arch/trimedia/board-mbe/mdsbslLcp_OsSpecific.c 
rm -f arch/trimedia/board-mbe/mdsbslLcp_IntDrv.c 
rm -f arch/trimedia/board-mbe/mdsbslLcp_Vid.h 
rm -f arch/trimedia/board-mbe/mdsbslLcp_Vid.c 
rm -f arch/trimedia/board-mbe/mdsbslLcp.h 
rm -f arch/trimedia/board-mbe/mdsbslLcp.c 
rm -f arch/trimedia/board-mbe/mdsbslLcp_Aud.h 
rm -f arch/trimedia/board-mbe/mdsbslLcp_Aud.c 
rm -f arch/trimedia/board-sim/tmbslNull.c 
rm -f arch/trimedia/board-sim/tmbslNull.h 
rm -f arch/trimedia/board-sim/tmbslNull_IntDrv.c 
rm -f arch/trimedia/board-sim/tmbslNull_IntDrv.h 
rm -f arch/trimedia/board-sim/tmbslNull_Mmio.h 
rm -f arch/trimedia/board-sim/tmbslNull_OsSpecific.c 
