#
# Makefile for arch/trimedia/bsp/tmBootInfo/src
#
EXTRA_CFLAGS = $(NDKCFLAGS) -Iarch/trimedia/bsp/tmBootInfo/ -DTMFL_OS_IS_PSOS=1 -DTMFL_CPU_IS_TM=1

obj-y += tmBootInfo.o tmMemUncached.o tmBootInfoUtil.o
